services:
  - type: web
    name: fishcard-bot
    env: python
    plan: free
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: ВСТАВЬ_СЮДА_СВОЙ_ТОКЕН
      - key: OPENAI_API_KEY
        value: ВСТАВЬ_СЮДА_СВОЙ_API_КЛЮЧ
