services:
  - type: web
    name: fishcard-bot
    env: python
    plan: free
    startCommand: "python main.py"
    autoDeploy: true
    pythonVersion: 3.10.11   # 👈 ключ, если runtime.txt не работает
